### ISSUE TITLE
Hi, I like this rule, why not PR to `eslint-mdx`?

### ISSUE THREAD

**Issue by JounQin** [ianlet/eslint-plugin-mdx-patch#1]

**Comment by ianlet** [comment]
Hi @JounQin ! Thanks for your message.

We could definitely make a PR to https://github.com/mdx-js/eslint-mdx but it would need more test cases to make sure it behaves correctly/as expected in most situations.

Also if I recall correctly, at the time I patched this there was a thread in `eslint-mdx` or `mdx` itself stating that the engine was being rewritten and that it will probably handle this issue by default (meaning it should support out of the box components without blank lines around/within it). I'll try to find it and link it here.

Knowing that, I didn't take time to make a PR to the repo, thinking it would have been resolved soon enough.

Edit: here's the issue https://github.com/mdx-js/mdx/issues/628

It seems to have been resolved though! But I don't know if it was released yet and if `eslint-mdx` upgraded to the new version.

If it's the case then this patch is no longer useful ☺️

**Comment by JounQin** [comment]
That's may be true for v2, but for now it's a good rule for v1.

**Comment by ianlet** [comment]
You're right!

Then would you mind trying different use cases with this rule and see if it breaks something or if something is not correctly linted/fixed? And open an issue/PR in this repo so I can addresses them?

Then I will fork the `eslint-mdx` repo to make a PR and add the rule directly there. Sounds good for you?

**Comment by JounQin** [comment]
You've already had test cases, so I think it's fine to PR directly and add it to the recommended config as warning by default. We can't test all eage cases, that's OK. Don't worry bout it.

**Comment by ianlet** [comment]
Alright I'll make a PR later today then.

**Comment by JounQin** [comment]
If you have any question about the source code or testing locally, feel free to ask me here.
